# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.10.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: anamarija.djuric2@gmail.com
author_name: AnaMarijaDjuric
preset_name: starter
project_name: UniChain-app

